### ISSUE TITLE
'rails s -e production' throws uninitialized constant AssetSync (NameError)

### ISSUE THREAD

**Issue by k504866430** [AssetSync/asset_sync#125]
I followed the installation and configuration steps and got the precompilation to sync with Amazon S3. But when I start the server in production mode using`rails s -e production`, I get this error-

```
/Users/kruttikagarwal/Documents/workspace-rails/tappedin/config/initializers/asset_sync.rb:1:in `<top (required)>': uninitialized constant AssetSync (NameError)
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/engine.rb:587:in `each'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/engine.rb:587:in `block in <class:Engine>'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `instance_exec'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/initializable.rb:30:in `run'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `each'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/initializable.rb:54:in `run_initializers'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/application.rb:136:in `initialize!'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /Users/kruttikagarwal/Documents/workspace-rails/tappedin/config/environment.rb:5:in `<top (required)>'
    from /Users/kruttikagarwal/Documents/workspace-rails/tappedin/config.ru:4:in `block in <main>'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/builder.rb:51:in `instance_eval'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/builder.rb:51:in `initialize'
    from /Users/kruttikagarwal/Documents/workspace-rails/tappedin/config.ru:1:in `new'
    from /Users/kruttikagarwal/Documents/workspace-rails/tappedin/config.ru:1:in `<main>'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/builder.rb:40:in `eval'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/builder.rb:40:in `parse_file'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/server.rb:200:in `app'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/commands/server.rb:46:in `app'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/server.rb:301:in `wrapped_app'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/rack-1.4.1/lib/rack/server.rb:252:in `start'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/commands/server.rb:70:in `start'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/commands.rb:55:in `block in <top (required)>'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/commands.rb:50:in `tap'
    from /Users/kruttikagarwal/.rvm/gems/ruby-1.9.3-p286@tappedin/gems/railties-3.2.8/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Interestingly enough, `rails s` (i.e development env) works just fine.

I precompiled my assets using-

```
RAILS_ENV=production bundle exec rake assets:precompile
```

**Comment by JackWells** [comment]
For me, fixed by deleting the file ./config/initializers/asset_sync.rb - which was created by running "rails g asset_sync:install" (in the instructions, including the modifications per-instructions), because it makes rails crash on start under ? conditions.

**Comment by PikachuEXE** [comment]
@JackWells 
Just changed the initializer template
at 9b2b3c1a6575e98312a38a416a676f79a47fc05e
Mind trying it? (Install the gem by git)
