### ISSUE TITLE
ArgumentError: aws is not a recognized storage provider

### ISSUE THREAD

**Issue by ericpeters0n** [AssetSync/asset_sync#319]
So, I'm testing out syncing Rails assets to my S3 bucket, and it appears asset_sync's downcasing of the provider name is creating issues in fog...?

```
$ export AWS_ACCESS_KEY_ID=xxx
$ export AWS_SECRET_ACCESS_KEY=yyy
$ export FOG_DIRECTORY=my-assets
$ export FOG_PROVIDER=AWS
$ bundle exec rake assets:precompile
```

yields--

```
...
Compiled foo_asset.html  (34ms)  (pid 35500)
** Invoke assets:sync (first_time)
** Invoke assets:environment 
** Execute assets:sync
AssetSync: Syncing.
rake aborted!
ArgumentError: aws is not a recognized storage provider
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/fog-core-1.29.0/lib/fog/storage.rb:27:in `new'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:15:in `connection'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:20:in `bucket'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:99:in `get_remote_files'
/Users/ericpeters0n/.rbenv/versions/1.9.3-p551/lib/ruby/gems/1.9.1/gems/asset_sync-1.1.0/lib/asset_sync/storage.rb:211:in `upload_files'
```

Any hints?

**Comment by PikachuEXE** [comment]
Can you try to config Asset sync this way?
```ruby
AssetSync.configure do |config|
    config.fog_provider           = 'AWS'
end
```
Trying to find out what's wrong :)

**Comment by PikachuEXE** [comment]
Closing until reproduced in latest version
