### ISSUE TITLE
cannot load such file -- mime/types (LoadError)

### ISSUE THREAD

**Issue by rickhull** [AssetSync/asset_sync#327]
to replicate:
```
mkdir asset_sync
cd asset_sync

cat << EOF > Gemfile
source 'https://rubygems.org'
gem "fog", require: "fog/aws/storage"
gem "asset_sync"
EOF

bundle

cat << EOF > test.rb
#!/usr/bin/env ruby

require 'asset_sync'
puts "DONE"
EOF

chmod 755 test.rb
bundle exec test.rb
```

Output:
```
/home/rwh/.gem/ruby/2.2.5/gems/asset_sync-1.1.0/lib/asset_sync/multi_mime.rb:1:in `require': cannot load such file -- mime/types (LoadError)
	from /home/rwh/.gem/ruby/2.2.5/gems/asset_sync-1.1.0/lib/asset_sync/multi_mime.rb:1:in `<top (required)>'
	from /home/rwh/.gem/ruby/2.2.5/gems/asset_sync-1.1.0/lib/asset_sync.rb:7:in `require'
	from /home/rwh/.gem/ruby/2.2.5/gems/asset_sync-1.1.0/lib/asset_sync.rb:7:in `<top (required)>'
	from test.rb:1:in `require'
	from test.rb:1:in `<main>'
```

**Comment by rickhull** [comment]
More environment details:

```
rwh@ip-172-40-0-16:~/src/fogtest$ ruby --version
ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-linux]
rwh@ip-172-40-0-16:~/src/fogtest$ gem --version
2.4.5.1
rwh@ip-172-40-0-16:~/src/fogtest$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.5 (2016-04-26 patchlevel 319) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/rwh/.gem/ruby/2.2.5
  - RUBY EXECUTABLE: /home/rwh/.rubies/ruby-2.2.5/bin/ruby
  - EXECUTABLE DIRECTORY: /home/rwh/.gem/ruby/2.2.5/bin
  - SPEC CACHE DIRECTORY: /home/rwh/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/rwh/.rubies/ruby-2.2.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/rwh/.gem/ruby/2.2.5
     - /home/rwh/.rubies/ruby-2.2.5/lib/ruby/gems/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/rwh/.gem/ruby/2.2.5/bin
     - /home/rwh/.rubies/ruby-2.2.5/lib/ruby/gems/2.2.0/bin
     - /home/rwh/.rubies/ruby-2.2.5/bin
     - /home/rwh/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /home/rwh/bin
     - ./bin
rwh@ip-172-40-0-16:~/src/fogtest$ cat Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (2.3.2)
    activemodel (4.2.6)
      activesupport (= 4.2.6)
      builder (~> 3.1)
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    asset_sync (1.1.0)
      activemodel
      fog (>= 1.8.0)
      unf
    builder (3.2.2)
    excon (0.49.0)
    fission (0.5.0)
      CFPropertyList (~> 2.2)
    fog (1.38.0)
      fog-aliyun (>= 0.1.0)
      fog-atmos
      fog-aws (>= 0.6.0)
      fog-brightbox (~> 0.4)
      fog-cloudatcost (~> 0.1.0)
      fog-core (~> 1.32)
      fog-dynect (~> 0.0.2)
      fog-ecloud (~> 0.1)
      fog-google (<= 0.1.0)
      fog-json
      fog-local
      fog-openstack
      fog-powerdns (>= 0.1.1)
      fog-profitbricks
      fog-rackspace
      fog-radosgw (>= 0.0.2)
      fog-riakcs
      fog-sakuracloud (>= 0.0.4)
      fog-serverlove
      fog-softlayer
      fog-storm_on_demand
      fog-terremark
      fog-vmfusion
      fog-voxel
      fog-vsphere (>= 0.4.0)
      fog-xenserver
      fog-xml (~> 0.1.1)
      ipaddress (~> 0.5)
    fog-aliyun (0.1.0)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      ipaddress (~> 0.8)
      xml-simple (~> 1.1)
    fog-atmos (0.1.0)
      fog-core
      fog-xml
    fog-aws (0.9.2)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-brightbox (0.10.1)
      fog-core (~> 1.22)
      fog-json
      inflecto (~> 0.0.2)
    fog-cloudatcost (0.1.2)
      fog-core (~> 1.36)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
      ipaddress (~> 0.8)
    fog-core (1.40.0)
      builder
      excon (~> 0.49)
      formatador (~> 0.2)
    fog-dynect (0.0.3)
      fog-core
      fog-json
      fog-xml
    fog-ecloud (0.3.0)
      fog-core
      fog-xml
    fog-google (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-json (1.0.2)
      fog-core (~> 1.0)
      multi_json (~> 1.10)
    fog-local (0.3.0)
      fog-core (~> 1.27)
    fog-openstack (0.1.6)
      fog-core (>= 1.39)
      fog-json (>= 1.0)
      ipaddress (>= 0.8)
    fog-powerdns (0.1.1)
      fog-core (~> 1.27)
      fog-json (~> 1.0)
      fog-xml (~> 0.1)
    fog-profitbricks (0.0.5)
      fog-core
      fog-xml
      nokogiri
    fog-rackspace (0.1.1)
      fog-core (>= 1.35)
      fog-json (>= 1.0)
      fog-xml (>= 0.1)
      ipaddress (>= 0.8)
    fog-radosgw (0.0.5)
      fog-core (>= 1.21.0)
      fog-json
      fog-xml (>= 0.0.1)
    fog-riakcs (0.1.0)
      fog-core
      fog-json
      fog-xml
    fog-sakuracloud (1.7.5)
      fog-core
      fog-json
    fog-serverlove (0.1.2)
      fog-core
      fog-json
    fog-softlayer (1.1.1)
      fog-core
      fog-json
    fog-storm_on_demand (0.1.1)
      fog-core
      fog-json
    fog-terremark (0.1.0)
      fog-core
      fog-xml
    fog-vmfusion (0.1.0)
      fission
      fog-core
    fog-voxel (0.1.0)
      fog-core
      fog-xml
    fog-vsphere (0.7.0)
      fog-core
      rbvmomi (~> 1.8)
    fog-xenserver (0.2.3)
      fog-core
      fog-xml
    fog-xml (0.1.2)
      fog-core
      nokogiri (~> 1.5, >= 1.5.11)
    formatador (0.2.5)
    i18n (0.7.0)
    inflecto (0.0.2)
    ipaddress (0.8.3)
    json (1.8.3)
    mini_portile2 (2.1.0)
    minitest (5.9.0)
    multi_json (1.12.1)
    nokogiri (1.6.8)
      mini_portile2 (~> 2.1.0)
      pkg-config (~> 1.1.7)
    pkg-config (1.1.7)
    rbvmomi (1.8.2)
      builder
      nokogiri (>= 1.4.1)
      trollop
    thread_safe (0.3.5)
    trollop (2.1.2)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.7.2)
    xml-simple (1.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  asset_sync
  fog

BUNDLED WITH
   1.12.5
```

**Comment by PikachuEXE** [comment]
Please try #328 to see if that fixes this issue :)

**Comment by rickhull** [comment]
Works!

**Comment by PikachuEXE** [comment]
Closing since #328 merged
