### ISSUE TITLE
"Too many open files" when having a lot of assets (files are opened but not closed)

### ISSUE THREAD

**Issue by zinkkrysty** [AssetSync/asset_sync#348]
We ran into this error on our server after precompilation of assets:

```
Excon::Error::Socket: Too many open files - getaddrinfo (Errno::EMFILE)
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/socket.rb:101:in `getaddrinfo’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/socket.rb:101:in `connect’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/ssl_socket.rb:153:in `connect’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/socket.rb:29:in `initialize’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/ssl_socket.rb:9:in `initialize’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:403:in `new’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:403:in `socket’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:100:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/mock.rb:48:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/instrumentor.rb:26:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:16:in `request_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:249:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/idempotent.rb:27:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/middlewares/base.rb:11:in `error_call’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:272:in `rescue in request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/excon-0.55.0/lib/excon/connection.rb:215:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/connection.rb:81:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-xml-0.1.2/lib/fog/xml/connection.rb:9:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/storage.rb:612:in `_request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/storage.rb:607:in `request’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/requests/storage/put_object.rb:47:in `put_object’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-aws-1.2.1/lib/fog/aws/models/storage/file.rb:219:in `save’
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/fog-core-1.43.0/lib/fog/core/collection.rb:51:in `create’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:208:in `upload_file’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:221:in `block in upload_files’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:219:in `each’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:219:in `upload_files’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/storage.rb:235:in `sync’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/asset_sync.rb:29:in `block in sync’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/asset_sync.rb:51:in `with_config’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/asset_sync/asset_sync.rb:28:in `sync’
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/tasks/asset_sync.rake:5:in `block (2 levels) in <top (required)>'
/home/deployer/au/shared/bundle/ruby/2.4.0/bundler/gems/asset_sync-5d3f776ff2eb/lib/tasks/asset_sync.rake:29:in `block in <top (required)>'
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/webpacker-1.2/lib/tasks/webpacker/compile.rake:40:in `block in <top (required)>'
/home/deployer/au/shared/bundle/ruby/2.4.0/gems/rake-11.3.0/exe/rake:27:in `<top (required)>'
/home/deployer/.rbenv/versions/2.4.0/bin/bundle:22:in `load’
/home/deployer/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
```

We investigated and realized that the process had opened more than 900 files around the moment the error surfaced.

We then looked at the code that uploaded each file and it seems that the files are opened but not closed:

https://github.com/AssetSync/asset_sync/blob/master/lib/asset_sync/storage.rb#L125

This is not good practice to open a bunch of files and not close them. Each file should be closed before opening the next one.

We managed to run `bundle exec rake 'assets:clean'` with a lower nr of assets to keep and then deployment worked again, however it is a matter of time until we increase the nr of assets so it reaches the max limit of files opened per process (1024).

**Comment by PikachuEXE** [comment]
Do you know any other ways to use fog without using `File.open`?
`File.open` is used in example code inside fog's doc:
http://fog.io/storage/

It might not be intended to be used on large number of file, but we need an alternative with some confidence to switch to.

**Comment by zinkkrysty** [comment]
I don't have much experience with fog and by looking at their docs and reading the source code I couldn't figure out where the code for the `create` method is, which could give us some clues of what input it expects.

Since the upload code is synchronous, it could also be possible to close the file just after

```
file = bucket.files.create( file ) unless ignore
```

What do you think?

**Comment by PikachuEXE** [comment]
Opened
https://github.com/fog/fog-core/issues/213
Let's wait for some responses

**Comment by zinkkrysty** [comment]
So, based on their answers it seems like the best option is to close the file after the upload (I guess the line I mentioned above would do) ? What do you think?

**Comment by PikachuEXE** [comment]
I guess it makes sense
But I need some time to figure out how to change it (coz I got a job :P
You can also try to change the code and test it yourself if you are able to
